# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 93d9af7c5e3ae0ec86e95a2402141f99ba444b8718b9955d46764f018c2ac5d8872f2ffbc4d2727d9e1647c19b0239a90a5a89225141742d7de031f77acf0322

test:
  secret_key_base: 1999ec7b97217f1e8f56efa60be58a734d63f8337dfc50d1b779c6ebbd43a986d73e0aad8060987863ac29380c160cfebcde5b6ef9da813e5d85cffa9c36e626

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
